### ISSUE TITLE
Improve imageReferences context vars

### ISSUE THREAD

**Issue by eddycharly** [kyverno/playground#128]
imageReferences context vars should work or an error/warning to be thrown. For images which are from private registries or otherwise cannot be resolved from the Playground, vars can be used with an order of precedence: live call => vars. If live call fails and vars not defined, throw an error. Do not score this as a pass, skip, or fail.

**Comment by chipzoller** [comment]
I didn't think through this comment enough. I think there's a slight problem here if I'm not mistaken. imageReferences is on a per-image basis and doesn't use a variable name that's user definable. So if this was to be supported outside of a live call to the registry, I think we would need a new method of supplying these contents in a static variable context way.

**Comment by eddycharly** [comment]
@chipzoller shall i close it ?

**Comment by chipzoller** [comment]
Do you think there's an improvement here? Like could we mock this up in a variables map somehow?

**Comment by eddycharly** [comment]
Do we have an example of what we are trying to fix ?

**Comment by chipzoller** [comment]
Take a look at this policy for example:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-base-images
  annotations:
    policies.kyverno.io/title: Allowed Base Images
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Building images which specify a base as their origin is a good start
      to improving supply chain security, but over time organizations
      may want to build an allow list of specific base images which
      are allowed to be used when constructing containers. This policy ensures
      that a container's base, found in an OCI annotation, is in a cluster-wide
      allow list.
spec:
  validationFailureAction: enforce
  rules:
  - name: check-base-image
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: NotEquals
        value: DELETE
    context:
    - name: baseimages
      configMap:
        name: baseimages
        namespace: platform
    validate:
      message: >-
        This container image's base is not in the approved list or is not specified. Only pre-approved
        base images may be used. Please contact the platform team for assistance.
      foreach:
      - list: "request.object.spec.containers"
        context:
        - name: imageData
          imageRegistry: 
            reference: "{{ element.image }}"
        - name: basename
          variable:
            jmesPath: imageData.manifest.annotations."org.opencontainers.image.base.name"
            default: ''
        deny:
          conditions:
            all:
              - key: "{{ basename }}"
                operator: AnyNotIn
                value: "{{ baseimages.data.allowedbaseimages }}"
```

This uses the `imageRegistry` type of context variable. This variable, unlike other context variables which are independent in nature, is dependent upon the image being referenced. It's also per image and not static like most other context vars. Docs for this are found [here](https://main.kyverno.io/docs/writing-policies/external-data-sources/#variables-from-image-registries). Look at the structure in the second code block. Both `manifest` and `configData` are objects themselves. What I'm suggesting is, if we wanted to be able to simulate and test these types of rules in cases where the registry CANNOT be reached, we'd have to be able to statically mock up the responses in a variables list. We could potentially do something like:

```yaml
kubernetes:
  version: '1.27'

context:
  username: 'system:serviceaccount:foo:safe'
  groups: []
  roles: []
  clusterRoles: []
  namespaceLabels: {}
  operation: CREATE

variables:
  imageRegistry:
    foo.corp.com/my/image:1.2.3:
      configData:
        jsonObjectGoesHere: {}
      manifest:
        jsonObjectGoesHere: {}
    foo.corp.com/mynext/image/4.5.6:
      etc.
```
```
